Repository MatheusMeira-Dev/soulpet-front-squad-5, pull requests merged in 2023-05, with the labels that each got.

#30 FE-11
  src/App.js
  src/components/Header/Header.jsx
  src/pages/Servicos/Servicos.jsx
Labels: enhancement

#31 Lista produtos
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/favicon.ico
  public/favicon1.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/App.js
  src/components/Header/Header.jsx
  src/index.css
  src/pages/Clientes/Clientes.jsx
  src/pages/EditaCliente/EditaCliente.jsx
  src/pages/EditaPet/EditaPet.jsx
  src/pages/NovoCliente/NovoCliente.jsx
  src/pages/Pets/Pets.css
  src/pages/Pets/Pets.jsx
  src/pages/Produtos/Produtos.jsx
Labels: documentation, enhancement

#32 :sparkles: feat Inserção de Novos Produtos FE-7
  public/index.html
  src/App.js
  src/index.css
  src/pages/NovoProduto/NovoProduto.css
  src/pages/NovoProduto/NovoProduto.jsx
  src/pages/Pets/Pets.css
  src/pages/Produtos/Produtos.jsx
Labels: documentation, enhancement

#33 Spt 10
  src/pages/Pets/Pets.jsx
  src/pages/Produtos/Produtos.jsx
Labels: bug, enhancement

#38 FE-10
  src/App.js
  src/pages/EditarServico/EditarServico.jsx
Labels: documentation, enhancement

#39 FE-9
  src/App.js
  src/pages/NovoServico/NovoServico.jsx
Labels: enhancement

#40 Fe 6
  src/pages/Produtos/Produtos.jsx
Labels: documentation, enhancement

#42 Gerar pdf
  package-lock.json
  package.json
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/manifest.json
  src/pages/Clientes/Clientes.jsx
  src/pages/EditaCliente/EditaCliente.jsx
  src/pages/EditaPet/EditaPet.jsx
  src/pages/EditarProduto/EditarProdutos.jsx
  src/pages/NovoCliente/NovoCliente.jsx
  src/pages/NovoProduto/NovoProduto.jsx
  src/pages/Pets/Pets.jsx
Labels: documentation, enhancement

#43 :sparkles:feat Listagem de Agendamento FE-15
  src/App.js
  src/components/Header/Header.jsx
  src/pages/Agendamentos/Agendamentos.jsx
Labels: enhancement

#44 Fe 14
  src/App.js
  src/pages/Agendamentos/Agendamentos.jsx
  src/pages/EditarAgendamento/EditarAgendamento.jsx
Labels: documentation, enhancement

#45 FE-13
  src/App.js
  src/pages/Agendamentos/Agendamentos.jsx
  src/pages/NovoAgendamento/NovoAgendamento.jsx
Labels: documentation, enhancement

#46 SPT-8
  src/pages/EditaCliente/EditaCliente.jsx
Labels: documentation, enhancement
